[package]
name = "actions-indexer-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.0.24"
uuid = {version = "1.18.0", features = ["serde"]}
serde = { version = "1", features = ["derive"] }
