[workspace]
members = [
    "stream",
    "indexer",
    "indexer_utils",
    "wire",
    "cache",
    "ipfs",
    
    "actions-indexer", 
    "actions-indexer-pipeline", 
    "actions-indexer-shared", 
]
resolver = "2"
