[workspace]
members = [
    "stream",
    "indexer",
    "indexer_utils",
    "wire",
    "cache",
    "ipfs",
    "wire", 
    
    "actions-indexer", 
    "actions-indexer-consumer", 
    "actions-indexer-processor", 
    "actions-indexer-loader", 
    "actions-indexer-types",
    "actions-indexer-orchestrator",
]
resolver = "2"
