[package]
name = "actions-indexer-consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
actions-indexer-types = { path = "../actions-indexer-types" }
tokio-stream = "0.1.17"
