[package]
name = "actions-indexer-consumer"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
futures03 = { version = "0.3.1", package = "futures", features = ["compat"] }
actions-indexer-types = { path = "../actions-indexer-types" }