[package]
name = "hermes-substream"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
substreams = "0.7"
substreams-ethereum = "0.11"
prost = "0.13"
prost-types = "0.13"
ethabi = "18.0.0"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
