[package]
name = "actions-indexer-repository"
version = "0.1.0"
edition = "2024"

[dependencies]
actions-indexer-shared = { path = "../actions-indexer-shared" }
async-trait = "0.1"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
thiserror = "1.0"
