apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: broker
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
  - target:
      kind: Job
      name: hermes-producer
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: hermes-producer:local
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: remove
        path: /spec/template/spec/imagePullSecrets
