apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Service
      name: broker
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
  - target:
      kind: StatefulSet
      name: kafka-broker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "PLAINTEXT://kafka-broker-0.broker.kafka.svc.cluster.local:29092,PLAINTEXT_HOST://localhost:9092"
